### ISSUE TITLE
Is PrimUnlifted IORef safe?

### ISSUE THREAD

**Issue by winterland1989** [haskell-primitive/primitive-unlifted#3]
I'm using `MVar` and `IORef`s instances from primitive-0.6.0 these days, but I'm not sure if they're still safe, could you help to explain the safety requirement of `PrimUnlifted` ?

**Comment by andrewthad** [comment]
The issues to look at are:

- https://github.com/haskell/primitive/issues/238
- https://gitlab.haskell.org/ghc/ghc/issues/16650
- https://gitlab.haskell.org/ghc/ghc/merge_requests/939 (In the comments, it becomes apparent that GHC is doing something wrong)
- https://gitlab.haskell.org/ghc/ghc/merge_requests/1030 (this is the fix to GHC)

The problem I encountered was that if I retrieved a `ByteArray` from an `UnliftedArray ByteArray` and then passed it to the C FFI, codegen was corrupted. There's no real reason to ever pass `IORef` or `MVar` to the C FFI, so storing these types in an `UnliftedArray` is totally safe.

I'll add `PrimUnlifted` instances for `IORef` and `MVar` to this library so that if you ever bump to `primitive-0.7`, you can use `primitive-unlifted` if you want. These instances will be sound even in the presence of C FFI calls in GHC < 8.10 since `ArrayArray#`, `MutVar#`, and `MVar#` all share the same C FFI offset (see `add_shim` in the GHC source although I changed it recently, so you'll need to go back several hundred commits).

**Comment by winterland1989** [comment]
Great, thanks for the clarification.

**Comment by andrewthad** [comment]
c6eca1b931f2f974a049507ef247b4cd06ce17f6 provides `PrimUnlifted` instances for `IORef` and `MVar`. This will be released later today.
